### ISSUE TITLE
Cannot read property 'min' of undefined

### ISSUE THREAD

**Issue by adipirro** [shoreditch-ops/artillery-plugin-statsd#3]
Currently looking into this myself, but I thought you guys may like to know. I'm seeing the following error message when I do a dead simple artillery run:

```
$ artillery run testFile.json 
Log file: artillery_report_20160929_230481.json
Phase 0 (Boring, quick phase) started - duration: 10s
 -/home/adipirro/.nvm/versions/node/v6.5.0/lib/node_modules/artillery-plugin-statsd/index.js:32
    metrics.gauge(prefix + '.latency.min', stats.latency.min || -1);
                                                        ^

TypeError: Cannot read property 'min' of undefined
    at EventEmitter.<anonymous> (/home/adipirro/.nvm/versions/node/v6.5.0/lib/node_modules/artillery-plugin-statsd/index.js:32:57)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Timeout.sendStats [as _repeat] (/home/adipirro/.nvm/versions/node/v6.5.0/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:209:8)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

testFile.json

```
{
  "config": {
    "target": "https://google.com",
    "phases": [
      {"duration": 10, "arrivalRate": 5, "name": "Boring, quick phase"}
    ],
    "plugins": {
      "statsd": {
        "host": "localhost",
        "port": 8125,
        "prefix": "artillery"
      }
    }
  },
  "scenarios": [
    {
      "flow": [
        {"get": {"url": "/"}}
      ]
    }
  ]
}

```

Artillery Version
`artillery@1.5.0-16 `

**Comment by hassy** [comment]
Need to investigate

**Comment by adipirro** [comment]
Found the problem :) Was about to fix it, but turns out that was already done in 51955b19c90561ab794c5168cf4bcfa99953d778

Turns out the npm package is just out of date...hasn't been updated in [7 months](https://www.npmjs.com/package/artillery-plugin-statsd)

I pointed at this repository directly, tested again, and everything is working as expected :+1:

**Comment by hassy** [comment]
Great, thanks @adipirro! I pushed a new release to npm.
